#include "gtest/gtest.h"
#include "ApprovalTests/Approvals.h"
#include "ApprovalTests/reporters/WindowsReporters.h"
#include "ApprovalTests/reporters/MacReporters.h"

using namespace ApprovalTests;

TEST(GoogleTestApprovalsTests, TestStreamableObject)
{
    Approvals::verify(42);
}

TEST(GoogleTestApprovalsTests, SpecificReporter)
{
    // begin-snippet: basic_approval_with_reporter
    Approvals::verify("text to be verified", Options(Windows::AraxisMergeReporter()));
    // end-snippet
}

TEST(GoogleTestApprovalsTests, SpecificReporter2)
{
    // begin-snippet: basic_approval_with_reporter_2
    Approvals::verify("text to be verified",
                      Options().withReporter(Mac::AraxisMergeReporter()));
    // end-snippet
}

TEST(GoogleTestApprovalsTests, CLionDemo) int getInt(int x) const
{
    return 0;
}

{
    // Trivial example code for https://youtrack.jetbrains.com/issue/CPP-1420
    int x = 2;
    int xsquared = x * x;
    EXPECT_EQ(xsquared, 4);
}
int GoogleTestApprovalsTests_CLionDemo_Test::getInt(int x) const
{
    int xsquared = x * x;
    return xsquared;
}

// Steps done:
// * Select line 32
// * Extract method
// * Click "OK"

// Output as generated by CLion 2020.3
// Build #CL-203.5981.166, built on December 1, 2020
